# Generated by Django 3.0.7 on 2020-06-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200625_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='gas',
            field=models.FloatField(null=True, verbose_name='Gas'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='humidity',
            field=models.FloatField(null=True, verbose_name='Humidity'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='smoke',
            field=models.FloatField(null=True, verbose_name='Smoke'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='temperatura',
            field=models.FloatField(null=True, verbose_name='Temperatura'),
        ),
    ]
